# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port = 8888
  autoLaunch = false

# Function specific settings
[functions]
  # Increase function timeout for Storacha operations
  node_bundler = "esbuild"
  external_node_modules = [
    "@web3-storage/w3up-client",
    "@ipld/car",
    "@ucanto/core",
    "@ipld/dag-ucan"
  ]
  included_files = ["netlify/functions/**/*"]

[functions.storacha-client]
  # Set appropriate timeouts for Storacha operations
  timeout = 30
  # Enable ESM
  format = "esm"

[build.environment]
  # Ensure proper Node version
  NODE_VERSION = "18"
  # Force HTTPS in production
  FORCE_HTTPS = "true"
  # Enable ESM
  NETLIFY_EXPERIMENTAL_BUILD_ESM_ALL = "true"

# Redirect API requests to functions with proper handling
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Force HTTPS

# Handle CORS for function endpoints
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"  # For development, in production change to your domain
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    Access-Control-Max-Age = "86400"

# Security headers for production
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Redirect for SPA - keep this last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 